default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: friend_development

test:
  <<: *default
  database: friend_test

production:
  <<: *default
  database: friend_production
  username: friend
  password: <%= ENV['FRIEND_DATABASE_PASSWORD'] %>
